# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_url', models.URLField()),
                ('host', models.CharField(choices=[('asana', 'asana')], max_length=24)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('permanent_url', models.URLField()),
                ('view_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(db_index=True, unique=True)),
                ('archived', models.BooleanField()),
                ('color', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_status', models.CharField(choices=[('inbox', 'inbox'), ('incoming', 'incoming'), ('later', 'later')], max_length=16, null=True)),
                ('due_date', models.DateField()),
                ('layout', models.CharField(choices=[('list', 'list')], max_length=16)),
                ('modified_at', models.DateTimeField()),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('notes', models.TextField()),
                ('public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(db_index=True, unique=True)),
                ('assignee_status', models.CharField(choices=[('inbox', 'inbox')], max_length=16)),
                ('completed', models.BooleanField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('due_on', models.DateField()),
                ('hearted', models.BooleanField()),
                ('modified_at', models.DateTimeField()),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('notes', models.TextField()),
                ('num_hearts', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('organization_id', models.IntegerField()),
                ('organization_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(db_index=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('photo', models.CharField(max_length=50, null=True, verbose_name='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.IntegerField(db_index=True, unique=True)),
                ('is_organization', models.BooleanField()),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='djasana.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='followers',
            field=models.ManyToManyField(related_name='tasks_following', to='djasana.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='hearts',
            field=models.ManyToManyField(to='djasana.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djasana.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='projects',
            field=models.ManyToManyField(to='djasana.Project'),
        ),
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djasana.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(related_name='projects_following', to='djasana.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='djasana.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_owned', to='djasana.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djasana.Team'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djasana.Workspace'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djasana.Task'),
        ),
    ]
