# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
