# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0003_auto_20170418_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=255, null=True, verbose_name='photo'),
        ),
    ]
