# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0004_auto_20170418_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='organization_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
