# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0005_auto_20170418_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
