# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0006_auto_20170418_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, help_text='The id of this object in Asana.', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, help_text='The id of this object in Asana.', unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, help_text='The id of this object in Asana.', unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, help_text='The id of this object in Asana.', unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, help_text='The id of this object in Asana.', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, help_text='The id of this object in Asana.', unique=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='remote_id',
            field=models.BigIntegerField(db_index=True, help_text='The id of this object in Asana.', unique=True),
        ),
    ]
