# Generated by Django 2.0.9 on 2018-10-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0007_adds_gid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='resource_subtype',
            field=models.CharField(blank=True, choices=[('enum', 'enum'), ('number', 'number'), ('text', 'text')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='customfieldsettings',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='resource_subtype',
            field=models.CharField(blank=True, choices=[('comment', 'comment'), ('system', 'system')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='resource_subtype',
            field=models.CharField(choices=[('default_task', 'default_task')], default='default_task', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='resource_type',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
