# Generated by Django 2.0.9 on 2018-11-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0009_adds_tag_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='resource_subtype',
            field=models.CharField(blank=True, choices=[('comment', 'comment'), ('system', 'system'), ('marked_incomplete', 'marked_incomplete')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='resource_subtype',
            field=models.CharField(choices=[('default_task', 'default_task')], default='default_task', max_length=24),
        ),
    ]
