# Generated by Django 2.1.3 on 2018-12-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0011_add_task_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_status', to='djasana.ProjectStatus'),
        ),
    ]
