# Generated by Django 2.1.3 on 2018-12-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0012_alters_project_current_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomFieldSettings', new_name='CustomFieldSetting'
        ),
        migrations.AddField(
            model_name='webhook',
            name='resource_type',
            field=models.CharField(blank=True, default='webhook', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='resource_type',
            field=models.CharField(blank=True, default='attachment', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='precision',
            field=models.SmallIntegerField(blank=True,
                                           choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                                                    (6, 6)], null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='resource_type',
            field=models.CharField(blank=True, default='custom_field', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(blank=True, choices=[('enum', 'enum'), ('number', 'number'), ('text', 'text')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='custom_field_settings',
            field=models.ManyToManyField(related_name='custom_field_settings', through='djasana.CustomFieldSetting', to='djasana.CustomField'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resource_type',
            field=models.CharField(blank=True, default='project', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='resource_type',
            field=models.CharField(blank=True, default='project_status', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='resource_subtype',
            field=models.CharField(blank=True, choices=[('comment', 'comment'), ('system', 'system'), ('added_to_project', 'added to project'), ('assigned', 'assigned'), ('comment_added', 'comment added'), ('description_changed', 'description changed'), ('due_date_changed', 'due date changed'), ('due_today', 'due today'), ('follower_added', 'follower added'), ('liked', 'liked'), ('marked_complete', 'marked complete'), ('marked_incomplete', 'marked_incomplete'), ('marked_today', 'marked today'), ('member_added', 'member added'), ('name_changed', 'name changed'), ('notes_changed', 'notes changed')], max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='resource_type',
            field=models.CharField(blank=True, default='story', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='source',
            field=models.CharField(choices=[('api', 'api'), ('email', 'email'), ('mobile', 'mobile'), ('web', 'web')], max_length=16),
        ),
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.CharField(blank=True, choices=[('comment', 'comment'), ('system', 'system')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='resource_type',
            field=models.CharField(blank=True, default='tag', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='resource_subtype',
            field=models.CharField(choices=[('default_task', 'default task'), ('section', 'section')], default='default_task', max_length=24),
        ),
        migrations.AlterField(
            model_name='task',
            name='resource_type',
            field=models.CharField(blank=True, default='task', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='resource_type',
            field=models.CharField(blank=True, default='team', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resource_type',
            field=models.CharField(blank=True, default='user', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='resource_type',
            field=models.CharField(blank=True, default='workspace', max_length=24, null=True),
        ),
    ]
