# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0013_auto_20170418_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
