# Generated by Django 2.1.3 on 2018-12-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0014_alter_custom_field_setting_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='resource_subtype',
            field=models.CharField(blank=True, choices=[('comment', 'comment'), ('system', 'system'), ('added_to_project', 'added to project'), ('all_dependencies_marked_complete', 'all_dependencies_marked_complete'), ('assigned', 'assigned'), ('comment_added', 'comment added'), ('dependency_marked_complete', 'dependency marked complete'), ('description_changed', 'description changed'), ('due_date_changed', 'due date changed'), ('due_today', 'due today'), ('follower_added', 'follower added'), ('liked', 'liked'), ('marked_complete', 'marked complete'), ('marked_incomplete', 'marked_incomplete'), ('marked_today', 'marked today'), ('member_added', 'member added'), ('name_changed', 'name changed'), ('notes_changed', 'notes changed')], max_length=48, null=True),
        ),
    ]
