# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0014_auto_20170418_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_status',
            field=models.CharField(choices=[('inbox', 'inbox'), ('upcoming', 'upcoming'), ('later', 'later')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_owned', to='djasana.User'),
        ),
    ]
