# Generated by Django 2.1.7 on 2019-07-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0016_alter_story_resource_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='due_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
