# Generated by Django 3.2.9 on 2021-11-10 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0023_alter_attachment_url_download_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djasana.user', to_field='remote_id'),
        ),
    ]
